gamma_S = 95.3; %Decay rate of P_1/2 state to S_1/2 in MHz
gamma_D = 31; %Decay rate of P_1/2 state to D_3/2 in MHz
%Omega_S = 10*gamma_S;
%Omega_D = 1*gamma_D;
Omega_S = 0.2*899.4180;
Omega_D = 0.2*1.4169e+03;
Delta_S = -2*pi*20;
Delta_D = -2*pi*200;

deltat = 0.000001;
t_end = 1;

t=0:deltat:t_end;
sigma_SS = nan(1,numel(t));
sigma_DD = nan(1,numel(t));
sigma_PP = nan(1,numel(t));
sigma_SD = nan(1,numel(t));
sigma_SP = nan(1,numel(t));
sigma_DP = nan(1,numel(t));
sigma_SS(:,1) = 1;
sigma_DD(:,1) = 0;
sigma_PP(:,1) = 0;
sigma_SD(:,1) = 0;
sigma_SP(:,1) = 0;
sigma_DP(:,1) = 0;

for h=2:numel(t)
    sigma_SS_k1 = (1i.*(Omega_S/2).*(sigma_SP(h-1)-conj(sigma_SP(h-1)))...
        +gamma_S.*sigma_PP(h-1)).*(t(h)-t(h-1));
    sigma_DD_k1 = (1i.*(Omega_D/2).*(sigma_DP(h-1)-conj(sigma_DP(h-1)))...
        +gamma_D.*sigma_PP(h-1)).*(t(h)-t(h-1));
    sigma_PP_k1 = (1i.*(Omega_S/2).*(-sigma_SP(h-1)+conj(sigma_SP(h-1)))...
        +1i.*(Omega_D/2).*(-sigma_DP(h-1)+conj(sigma_DP(h-1)))...
        -(gamma_S + gamma_D).*sigma_PP(h-1)).*(t(h)-t(h-1));
    sigma_SD_k1 = (1i.*(Omega_D/2).*sigma_SP(h-1)...
        -1i.*(Delta_S-Delta_D).*sigma_SD(h-1)...
        -1i.*(Omega_S/2).*conj(sigma_DP(h-1))).*(t(h)-t(h-1));
    sigma_SP_k1 = (1i.*(Omega_S/2).*(sigma_SS(h-1)-sigma_PP(h-1))...
        +1i.*(Omega_D/2).*sigma_SD(h-1)...
        -1i.*Delta_S.*sigma_SP(h-1)...
        -((gamma_S+gamma_D)./2).*sigma_SP(h-1)).*(t(h)-t(h-1));
    sigma_DP_k1 = (1i.*(Omega_D/2).*(sigma_DD(h-1)-sigma_PP(h-1))...
        +1i.*(Omega_S/2).*conj(sigma_SD(h-1))...
        -1i.*Delta_D.*sigma_DP(h-1)...
        -((gamma_S+gamma_D)./2).*sigma_DP(h-1)).*(t(h)-t(h-1));
    
    sigma_SS_k2 = (1i.*(Omega_S/2).*((sigma_SP(h-1)+sigma_SP_k1/2)-conj(sigma_SP(h-1)+sigma_SP_k1/2))...
        +gamma_S.*(sigma_PP(h-1)+sigma_PP_k1/2)).*(t(h)-t(h-1));
    sigma_DD_k2 = (1i.*(Omega_D/2).*((sigma_DP(h-1)+sigma_DP_k1/2)-conj(sigma_DP(h-1)+sigma_DP_k1/2))...
        +gamma_D.*(sigma_PP(h-1)+sigma_PP_k1/2)).*(t(h)-t(h-1));
    sigma_PP_k2 = (1i.*(Omega_S/2).*(-(sigma_SP(h-1)+sigma_SP_k1/2)+conj(sigma_SP(h-1)+sigma_SP_k1/2))...
        +1i.*(Omega_D/2).*(-(sigma_DP(h-1)+sigma_DP_k1/2)+conj(sigma_DP(h-1)+sigma_DP_k1/2))...
        -(gamma_S + gamma_D).*(sigma_PP(h-1)-sigma_PP_k1/2)).*(t(h)-t(h-1));
    sigma_SD_k2 = (1i.*(Omega_D/2).*(sigma_SP(h-1)+sigma_SP_k1/2)...
        -1i.*(Delta_S-Delta_D).*(sigma_SD(h-1)+sigma_SD_k1/2)...
        -1i.*(Omega_S/2).*conj(sigma_DP(h-1)+sigma_DP_k1/2)).*(t(h)-t(h-1));
    sigma_SP_k2 = (1i.*(Omega_S/2).*((sigma_SS(h-1)+sigma_SS_k1/2)-(sigma_PP(h-1)+sigma_PP_k1/2))...
        +1i.*(Omega_D/2).*(sigma_SD(h-1)+sigma_SD_k1/2)...
        -1i.*Delta_S.*(sigma_SP(h-1)+sigma_SP_k1/2)...
        -((gamma_S+gamma_D)./2).*(sigma_SP(h-1)+sigma_SP_k1/2)).*(t(h)-t(h-1));
    sigma_DP_k2 = (1i.*(Omega_D/2).*((sigma_DD(h-1)+sigma_DD_k1/2)-(sigma_PP(h-1)+sigma_PP_k1/2))...
        +1i.*(Omega_S/2).*conj(sigma_SD(h-1)+sigma_SD_k1/2)...
        -1i.*Delta_D.*(sigma_DP(h-1)+sigma_DP_k1/2)...
        -((gamma_S+gamma_D)./2).*(sigma_DP(h-1)+sigma_DP_k1/2)).*(t(h)-t(h-1));
    
    sigma_SS_k3 = (1i.*(Omega_S/2).*((sigma_SP(h-1)+sigma_SP_k2/2)-conj(sigma_SP(h-1)+sigma_SP_k2/2))...
        +gamma_S.*(sigma_PP(h-1)+sigma_PP_k2/2)).*(t(h)-t(h-1));
    sigma_DD_k3 = (1i.*(Omega_D/2).*((sigma_DP(h-1)+sigma_DP_k2/2)-conj(sigma_DP(h-1)+sigma_DP_k2/2))...
        +gamma_D.*(sigma_PP(h-1)+sigma_PP_k2/2)).*(t(h)-t(h-1));
    sigma_PP_k3 = (1i.*(Omega_S/2).*(-(sigma_SP(h-1)+sigma_SP_k2/2)+conj(sigma_SP(h-1)+sigma_SP_k2/2))...
        +1i.*(Omega_D/2).*(-(sigma_DP(h-1)+sigma_DP_k2/2)+conj(sigma_DP(h-1)+sigma_DP_k2/2))...
        -(gamma_S + gamma_D).*(sigma_PP(h-1)-sigma_PP_k2/2)).*(t(h)-t(h-1));
    sigma_SD_k3 = (1i.*(Omega_D/2).*(sigma_SP(h-1)+sigma_SP_k2/2)...
        -1i.*(Delta_S-Delta_D).*(sigma_SD(h-1)+sigma_SD_k2/2)...
        -1i.*(Omega_S/2).*conj(sigma_DP(h-1)+sigma_DP_k2/2)).*(t(h)-t(h-1));
    sigma_SP_k3 = (1i.*(Omega_S/2).*((sigma_SS(h-1)+sigma_SS_k2/2)-(sigma_PP(h-1)+sigma_PP_k2/2))...
        +1i.*(Omega_D/2).*(sigma_SD(h-1)+sigma_SD_k2/2)...
        -1i.*Delta_S.*(sigma_SP(h-1)+sigma_SP_k2/2)...
        -((gamma_S+gamma_D)./2).*(sigma_SP(h-1)+sigma_SP_k2/2)).*(t(h)-t(h-1));
    sigma_DP_k3 = (1i.*(Omega_D/2).*((sigma_DD(h-1)+sigma_DD_k2/2)-(sigma_PP(h-1)+sigma_PP_k2/2))...
        +1i.*(Omega_S/2).*conj(sigma_SD(h-1)+sigma_SD_k2/2)...
        -1i.*Delta_D.*(sigma_DP(h-1)+sigma_DP_k2/2)...
        -((gamma_S+gamma_D)./2).*(sigma_DP(h-1)+sigma_DP_k2/2)).*(t(h)-t(h-1));
    
    sigma_SS_k4 = (1i.*(Omega_S/2).*((sigma_SP(h-1)+sigma_SP_k3)-conj(sigma_SP(h-1)+sigma_SP_k3))...
        +gamma_S.*(sigma_PP(h-1)+sigma_PP_k3)).*(t(h)-t(h-1));
    sigma_DD_k4 = (1i.*(Omega_D/2).*((sigma_DP(h-1)+sigma_DP_k3)-conj(sigma_DP(h-1)+sigma_DP_k3))...
        +gamma_D.*(sigma_PP(h-1)+sigma_PP_k3)).*(t(h)-t(h-1));
    sigma_PP_k4 = (1i.*(Omega_S/2).*(-(sigma_SP(h-1)+sigma_SP_k3)+conj(sigma_SP(h-1)+sigma_SP_k3))...
        +1i.*(Omega_D/2).*(-(sigma_DP(h-1)+sigma_DP_k3)+conj(sigma_DP(h-1)+sigma_DP_k3))...
        -(gamma_S + gamma_D).*(sigma_PP(h-1)-sigma_PP_k3)).*(t(h)-t(h-1));
    sigma_SD_k4 = (1i.*(Omega_D/2).*(sigma_SP(h-1)+sigma_SP_k3)...
        -1i.*(Delta_S-Delta_D).*(sigma_SD(h-1)+sigma_SD_k3)...
        -1i.*(Omega_S/2).*conj(sigma_DP(h-1)+sigma_DP_k3)).*(t(h)-t(h-1));
    sigma_SP_k4 = (1i.*(Omega_S/2).*((sigma_SS(h-1)+sigma_SS_k3)-(sigma_PP(h-1)+sigma_PP_k3))...
        +1i.*(Omega_D/2).*(sigma_SD(h-1)+sigma_SD_k3)...
        -1i.*Delta_S.*(sigma_SP(h-1)+sigma_SP_k3)...
        -((gamma_S+gamma_D)./2).*(sigma_SP(h-1)+sigma_SP_k3)).*(t(h)-t(h-1));
    sigma_DP_k4 = (1i.*(Omega_D/2).*((sigma_DD(h-1)+sigma_DD_k3)-(sigma_PP(h-1)+sigma_PP_k3))...
        +1i.*(Omega_S/2).*conj(sigma_SD(h-1)+sigma_SD_k3)...
        -1i.*Delta_D.*(sigma_DP(h-1)+sigma_DP_k3)...
        -((gamma_S+gamma_D)./2).*(sigma_DP(h-1)+sigma_DP_k3)).*(t(h)-t(h-1));
    
    sigma_SS(h) = sigma_SS(h-1) + (1/6).*(sigma_SS_k1+2.*sigma_SS_k2+2.*sigma_SS_k3+sigma_SS_k4);
    sigma_DD(h) = sigma_DD(h-1) + (1/6).*(sigma_DD_k1+2.*sigma_DD_k2+2.*sigma_DD_k3+sigma_DD_k4);
    sigma_PP(h) = sigma_PP(h-1) + (1/6).*(sigma_PP_k1+2.*sigma_PP_k2+2.*sigma_PP_k3+sigma_PP_k4);
    sigma_SD(h) = sigma_SD(h-1) + (1/6).*(sigma_SD_k1+2.*sigma_SD_k2+2.*sigma_SD_k3+sigma_SD_k4);
    sigma_SP(h) = sigma_SP(h-1) + (1/6).*(sigma_SP_k1+2.*sigma_SP_k2+2.*sigma_SP_k3+sigma_SP_k4);
    sigma_DP(h) = sigma_DP(h-1) + (1/6).*(sigma_DP_k1+2.*sigma_DP_k2+2.*sigma_DP_k3+sigma_DP_k4);
end